//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "Lab9.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/uart.h"
#include "inc/tm4c123gh6pm.h"

#define 	RED_MASK 			0x02
#define 	BLUE_MASK 		0x04
#define 	GREEN_MASK 		0x08

//*****************************************************************************

char error[] = "Invalid Input";
char prompt[] = "Enter Text:\n\r";
void PortFunctionInit(void)
{
		// Sets Clock to 100 MHz	
		SysCtlClockSet(SYSCTL_SYSDIV_4 | SYSCTL_USE_PLL | SYSCTL_OSC_MAIN | SYSCTL_XTAL_16MHZ);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);

		// Enable pins PA0,PA1 for UART
    GPIOPinConfigure(GPIO_PA0_U0RX);
    GPIOPinConfigure(GPIO_PA1_U0TX);
    GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);

    
    // Enable Peripheral Clocks 
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    // Enable pins PF1-3 for GPIOOutput
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3);
		
		//Configure UART serial port
		UARTConfigSetExpClk(UART0_BASE, SysCtlClockGet(), 115200,
        (UART_CONFIG_WLEN_8 | UART_CONFIG_STOP_ONE | UART_CONFIG_PAR_NONE));
}

void UARTIntHandler(void)
{
    uint32_t ui32Status;
    ui32Status = UARTIntStatus(UART0_BASE, true); //get interrupt status
		char c;
		bool valid;

    UARTIntClear(UART0_BASE, ui32Status); //clear the asserted interrupts

    while(UARTCharsAvail(UART0_BASE)) //loop while there are chars
    {
				c = UARTCharGet(UART0_BASE);
				valid = 1;

				//Perform Action based on Keyboard Input
				switch(c)
				{
					//Turn off Red LED if 'r' is entered
					case 'r':
						GPIO_PORTF_DATA_R &= ~RED_MASK;
						break;
					//Turn on Red LED if 'R' is entered
					case 'R':
						GPIO_PORTF_DATA_R |= RED_MASK;
						break;
					
					//Turn off Green LED if 'g' is entered
					case 'g':
						GPIO_PORTF_DATA_R &= ~GREEN_MASK;
						break;
					//Turn on Green LED if 'G' is entered
					case 'G':
						GPIO_PORTF_DATA_R |= GREEN_MASK;
						break;
					
					//Turn off Blue LED if 'b' is entered
					case 'b':
						GPIO_PORTF_DATA_R &= ~BLUE_MASK;
						break;
					//Turn on Blue LED if 'B' is entered
					case 'B':
						GPIO_PORTF_DATA_R |= BLUE_MASK;
						break;
					
					//Print Error Message if anything else is entered
					default:
						valid = 0;
						for(int i = 0; i < sizeof(error); i++)
								UARTCharPut(UART0_BASE, error[i]);
						
				}
				
				//Echo character if valid input
				if(valid)
					UARTCharPut(UART0_BASE, c);
				
				//Place Cursor at the beginning of the next line
				UARTCharPut(UART0_BASE, '\n');
				UARTCharPut(UART0_BASE, '\r');
    }
}

int main(void) {
		
		PortFunctionInit(); // Initialize Ports
    IntMasterEnable(); //enable processor interrupts
    IntEnable(INT_UART0); //enable the UART interrupt
    UARTIntEnable(UART0_BASE, UART_INT_RX | UART_INT_RT); //only enable RX and TX interrupts

		//Prompt User to Enter Text
    for(int i = 0; i < sizeof(prompt); i++)
				UARTCharPut(UART0_BASE, prompt[i]);
		

    while (1)
    {
			
    }

}
