//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "Lab6.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"
#include "inc/tm4c123gh6pm.h"

#define 	LED1_MASK 		0x02
#define 	LED2_MASK 		0x04
//*****************************************************************************
void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF2 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);

    //
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF4 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PF1 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);
		
		//Enable pull-up on PF0 and PF4
		GPIO_PORTF_PUR_R |= 0x11;
		
		// Sets the clock to 40MHz
		SysCtlClockSet(SYSCTL_SYSDIV_5|SYSCTL_USE_PLL|SYSCTL_XTAL_16MHZ|SYSCTL_OSC_MAIN);
}

int main(void)
{
	
		//initialize the GPIO ports	
		PortFunctionInit();
	
		uint8_t LED1_data = LED1_MASK;
		uint8_t LED2_data = LED2_MASK;
	
    //
    // Loop forever.
    //
    while(1)
    {
			if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)==0x00) //SW2 is pressed
			{
				// Turn off the Blue LED.
				LED2_data &= ~LED2_MASK;
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, LED2_data);
					
				// Turn off the Red LED.
				LED1_data &= ~LED1_MASK;
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, LED1_data);
			}
			else if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)==0x00) //SW1 is pressed
			{
				// Turn off the Blue LED.
				LED2_data &= ~LED2_MASK;
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, LED2_data);
						
				// Delay for at most, half a second.
				for(int i = 0; i < 25; i++)
				{
					// Delay for twenty milliseconds.
					SysCtlDelay(SysCtlClockGet()/150);
					
					// SW1 is released or SW2 is pressed
					if(!(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)==0x00) || (GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)==0x00)) 
					{
						i = 25;
					}
				}

				// Toggle the Red LED.
				LED1_data^=LED1_MASK;
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, LED1_data);
			}
			else //SW1 is released
			{
				// Turn off the Red LED.
				LED1_data &= ~LED1_MASK;
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, LED1_data);
				
				// Delay for at most, half a second.
				for(int i = 0; i < 25; i++)
				{
					// Delay for twenty milliseconds.
					SysCtlDelay(SysCtlClockGet()/150);
					
					// SW1 or SW2 is pressed
					if((GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)==0x00) || (GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)==0x00))
					{
						i = 25;
					}
				}
				// Toggle the Blue LED.
				LED2_data^=LED2_MASK;
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, LED2_data);
			}
		
   }
}
